
import Joi from "joi";

export const alphaNumericNameRule = Joi.string()
  .min(3)
  .max(100)
  .pattern(/^(?=.*[A-Za-z])[A-Za-z0-9\s.&'-]+$/) // must contain at least one letter
  .required()
  .messages({
    "string.empty": "Branch Name is required",
    "string.min": "Name must be at least 3 characters",
    "string.max": "Name must be at most 100 characters",
    "string.pattern.base":
      "Branch Name must contain at least one letter and can only include letters, numbers, spaces, . & ' -",
  });

  
export const nameRule = Joi.string()
  .pattern(/^(?!\d+$)[A-Za-z][A-Za-z\s.&'-]*$/) // no numbers-only, must start with a letter
  .min(3)
  .max(100)
  .required()
  .messages({
    "string.empty": "Name is required",
    "string.min": "Name must be at least 3 characters",
    "string.max": "Name must be at most 100 characters",
    "string.pattern.base":
      "Name must start with a letter and can only contain letters, spaces, dots, apostrophes, ampersands, or hyphens (not numbers only)",
  });

export const addressRule = Joi.string()
  .min(5)
  .max(200)
  .pattern(/^(?!\d+$)[A-Za-z0-9\s,.-/]*$/) // not only numbers, allow letters, digits, spaces, , . - /
  .required()
  .messages({
    "string.empty": "Address is required",
    "string.min": "Address must be at least 5 characters",
    "string.max": "Address cannot exceed 200 characters",
    "string.pattern.base": "Address must not be only numbers and can include letters, numbers, spaces, , . - /",
  });


  // A specific rule for the categories type dropdown
// A specific rule for the categories type dropdown
export const categoriesTypeRule = Joi.string()
    .valid(
        "Academic",
        "Competitive Exam",
        "Professional",
        "Skill Development",
        "Language",
        "Arts & Crafts",
        "Sports",
        "Music & Dance",
        "Exam Preparation",
        "Upskilling"
    )
    .required()
    .messages({
        "string.empty": "Please select a categories type.",
        "any.required": "Please select a categories type.",
        "any.only": "Please select a valid categories type from the list."
    });

// A specific rule for the domain type dropdown
export const domainTypeRule = Joi.string()
    .valid(
        "Engineering",
        "Medical",
        "Management",
        "Law",
        "Banking",
        "Government Jobs",
        "IT & Software",
        "Design",
        "Marketing",
        "Finance",
        "Civil Services & Administrative",
        "Banking Exams",
        "Insurance Exams",
        "Railways Exams",
        "SSC Exams (Staff Selection Commission)",
        "Defence Exams",
        "Police & Law Enforcement",
        "Teaching Exams",
        "Legal & Judicial Services",
        "State Government Exams",
        "Central Government Recruitment",
        "Research & Scientific",
        "Other Government Exams",
        "ENGINEERING ENTRANCE EXAMS - INDIA",
        "Architecture Entrance",
        "MEDICAL ENTRANCE EXAMS - INDIA",
        "Physiotherapy Entrance Exams",
        "MANAGEMENT ENTRANCE EXAMS - INDIA",
        "LAW ENTRANCE EXAMS - INDIA",
        "DESIGN & CREATIVE ENTRANCE EXAMS - INDIA",
        "HOTEL MANAGEMENT & HOSPITALITY EXAMS - INDIA",
        "MASS COMMUNICATION & JOURNALISM - INDIA",
        "OTHER PROFESSIONAL ENTRANCE EXAMS - INDIA",
        "SCHOOL/FOUNDATION LEVEL EXAMS - INDIA",
        "INTERNATIONAL EXAMS",
        "Programming Languages",
          "Web Development",
          "Mobile App Development",
          "Database & Backend",
          "DevOps & Cloud",
          "Data Science & Analytics",
          "Artificial Intelligence & Machine Learning",
          "Cyber Security",
          "Blockchain & Emerging Tech",
          "Software Testing & QA",
          "UI/UX & Design Tech",
          "IT Management & Architecture",
          "Game Development",
          "Specialized IT Areas",
          "Graphic Design & Visual Arts",
          "Video & Motion Graphics",
          "Photography",
          "Music & Audio",
          "Beauty & Wellness",
          "Fashion & Styling",
          "Marketing & Sales",
          "Business Management",
          "Finance & Accounting",
          "Human Resources",
          "Supply Chain & Logistics",
          "Language Learning",
          "Communication & Soft Skills",
          "Health & Fitness",
          "Culinary Arts & Food",
          "Performing Arts",
          "Craft & DIY",
          "Interior Design & Home Decor",
          "Event Management & Hospitality",
          "Automobile & Mechanics",
          "Other Vocational Skills",
          "Real Estate",
          "Agriculture & Farming",
          "Pet Care"

    )
    .required()
    .messages({
        "string.empty": "Please select a domain type.",
        "any.required": "Please select a domain type.",
        "any.only": "Please select a valid domain type from the list."
    });

export const subDomainTypeRule = Joi.string()
    .valid(
        // "Engineering",
        // "Medical",
        // "Management",
        // "Law",
        // "Banking",
        // "Government Jobs",
        // "IT & Software",
        // "Design",
        // "Marketing",
        // "Finance"
        "UPSC Civil Services Examination (IAS/IPS/IFS)",
          "UPSC Prelims",
          "UPSC Mains",
          "UPSC Interview/Personality Test",
          "State Public Service Commission (State PSC)",
          "BPSC (Bihar)",
          "MPPSC (Madhya Pradesh)",
          "UPPSC (Uttar Pradesh)",
          "RPSC (Rajasthan)",
          "GPSC (Gujarat)",
          "KPSC (Karnataka)",
          "TNPSC (Tamil Nadu)",
          "WBPSC (West Bengal)",
          "APPSC (Andhra Pradesh)",
          "TSPSC (Telangana)",
          "CGPSC (Chhattisgarh)",
          "UKPSC (Uttarakhand)",
          "HPPSC (Himachal Pradesh)",
          "PPSC (Punjab)",
          "JKPSC (Jammu & Kashmir)",
          "APSC (Assam)",
          "MPSC (Maharashtra)",
          "KPSC (Kerala)",
          "IBPS PO (Probationary Officer)",
          "IBPS Clerk",
          "IBPS SO (Specialist Officer)",
          "IBPS RRB (Regional Rural Banks)",
          "SBI PO",
          "SBI Clerk",
          "SBI SO",
          "RBI Grade B",
          "RBI Assistant",
          "NABARD Grade A & B",
          "SIDBI",
          "SEBI Grade A",
          "IPPB (India Post Payment Bank)",
          "Cooperative Bank Exams",
          "LIC AAO (Assistant Administrative Officer)",
          "LIC ADO (Apprentice Development Officer)",
          "LIC HFL (Housing Finance Limited)",
          "NIACL (New India Assurance)",
          "OICL (Oriental Insurance)",
          "UIIC (United India Insurance)",
          "GIC (General Insurance Corporation)",
          "RRB NTPC (Non-Technical Popular Categories)",
          "RRB Group D",
          "RRB JE (Junior Engineer)",
          "RRB ALP (Assistant Loco Pilot)",
          "RRB RPF (Railway Protection Force)",
          "RRB Technician",
          "DFCCIL (Dedicated Freight Corridor Corporation)",
          "RITES (Rail India Technical & Economic Service)",
          "IRCTC",
          "CONCOR",
          "SSC CGL (Combined Graduate Level)",
          "SSC CHSL (Combined Higher Secondary Level)",
          "SSC CPO (Central Police Organisation)",
          "SSC GD (General Duty)",
          "SSC JE (Junior Engineer)",
          "SSC MTS (Multi-Tasking Staff)",
          "SSC Stenographer",
          "SSC Selection Post",
          "SSC Scientific Assistant",
          "NDA (National Defence Academy)",
          "CDS (Combined Defence Services)",
          "AFCAT (Air Force Common Admission Test)",
          "Indian Army TGC/TES",
          "Indian Navy Entrance",
          "Indian Air Force",
          "INET (Indian Navy Entrance Test)",
          "Territorial Army",
          "Coast Guard",
          "Military Nursing Service",
          "Para Military Forces",
          "CAPF (Central Armed Police Forces)",
          "CRPF (Central Reserve Police Force)",
          "BSF (Border Security Force)",
          "CISF (Central Industrial Security Force)",
          "ITBP (Indo-Tibetan Border Police)",
          "SSB (Sashastra Seema Bal)",
          "Assam Rifles",
          "NSG (National Security Guard)",
          "State Police Constable",
          "State Police SI (Sub-Inspector)",
          "Delhi Police",
          "Mumbai Police",
          "CTET (Central Teacher Eligibility Test)",
          "State TET (All States)",
          "UGC NET (National Eligibility Test)",
          "CSIR NET",
          "SLET/SET (State Level Eligibility Test)",
          "KVS (Kendriya Vidyalaya Sangathan)",
          "NVS (Navodaya Vidyalaya Samiti)",
          "DSSSB (Delhi Subordinate Services Selection Board)",
          "Army Public School Teachers",
          "AWES (Army Welfare Education Society)",
          "CLAT PG (Common Law Admission Test)",
          "Judicial Services (All States)",
          "AIBE (All India Bar Examination)",
          "District Judge Exam",
          "Civil Judge Exam",
          "Judicial Magistrate",
          "Law Officer Exams",
          "Group A, B, C, D Posts (All States)",
          "Patwari Exam",
          "Revenue Inspector",
          "Village Accountant",
          "Gram Sevak",
          "Panchayat Secretary",
          "Block Development Officer",
          "Tehsildar",
          "Lekhpal",
          "UPPCL (Uttar Pradesh Power Corporation)",
          "State Electricity Boards",
          "FCI (Food Corporation of India)",
          "ESIC (Employees' State Insurance Corporation)",
          "EPFO (Employees' Provident Fund Organisation)",
          "NHM (National Health Mission)",
          "NRHM (National Rural Health Mission)",
          "India Post GDS/Postman/Mail Guard",
          "DRDO (Defence Research & Development Organisation)",
          "ISRO (Indian Space Research Organisation)",
          "BARC (Bhabha Atomic Research Centre)",
          "BHEL (Bharat Heavy Electricals Limited)",
          "ONGC (Oil & Natural Gas Corporation)",
          "IOCL (Indian Oil Corporation)",
          "BPCL (Bharat Petroleum Corporation)",
          "HPCL (Hindustan Petroleum Corporation)",
          "GAIL (Gas Authority of India Limited)",
          "Coal India Limited",
          "NTPC (National Thermal Power Corporation)",
          "Power Grid Corporation",
          "HAL (Hindustan Aeronautics Limited)",
          "BEL (Bharat Electronics Limited)",
          "SAIL (Steel Authority of India Limited)",
          "AAI (Airports Authority of India)",
          "CSIR NET",
          "GATE (Graduate Aptitude Test in Engineering)",
          "JEST (Joint Entrance Screening Test)",
          "JGEEBILS (Joint GATE Entrance Examination for Biology & Life Sciences)",
          "TIFR (Tata Institute of Fundamental Research)",
          "IISc Admission Test",
          "IISER Aptitude Test",
          "Lok Sabha Secretariat",
          "Rajya Sabha Secretariat",
          "Election Commission of India",
          "CAG (Comptroller & Auditor General)",
          "Supreme Court of India",
          "High Court Recruitment",
          "Intelligence Bureau (IB)",
          "Research & Analysis Wing (RAW)",
          "CBI (Central Bureau of Investigation)",
          "NIA (National Investigation Agency)",
          "ED (Enforcement Directorate)",
          "JEE Main",
          "JEE Advanced",
          "BITSAT (Birla Institute of Technology & Science)",
          "VITEEE (VIT Engineering Entrance Exam)",
          "SRMJEEE (SRM Joint Engineering Entrance Exam)",
          "COMEDK UGET",
          "MET (Manipal Entrance Test)",
          "AEEE (Amrita Engineering Entrance Exam)",
          "KIITEE (Kalinga Institute of Industrial Technology)",
          "WBJEE (West Bengal Joint Entrance Exam)",
          "UPSEE/UPTU (Uttar Pradesh State Entrance Exam)",
          "KCET (Karnataka Common Entrance Test)",
          "TNEA (Tamil Nadu Engineering Admissions)",
          "AP EAMCET (Andhra Pradesh Engineering Common Entrance Test)",
          "TS EAMCET (Telangana State Engineering Common Entrance Test)",
          "MHT CET (Maharashtra Common Entrance Test)",
          "GUJCET (Gujarat Common Entrance Test)",
          "KEAM (Kerala Engineering Architecture Medical)",
          "OJEE (Odisha Joint Entrance Exam)",
          "BCECE (Bihar Combined Entrance Competitive Exam)",
          "JCECE (Jharkhand Combined Entrance Competitive Exam)",
          "CGPET (Chhattisgarh Pre-Engineering Test)",
          "RPET (Rajasthan Pre-Engineering Test)",
          "MP JEE (Madhya Pradesh Joint Entrance Exam)",
          "NATA (National Aptitude Test in Architecture)",
          "JEE Main Paper 2 (B.Arch)",
          "AAT (Architecture Aptitude Test - After JEE Advanced)",
          "NEET UG (Undergraduate)",
          "NEET PG (Postgraduate)",
          "NEET SS (Super Specialty)",
          "NEET MDS (Master of Dental Surgery)",
          "AIIMS Nursing",
          "INI CET (Institute of National Importance Combined Entrance Test)",
          "Allied Medical & Paramedical",
          "JIPMER Nursing",
          "BHU Nursing",
          "PGIMER Nursing",
          "AIIMS B.Sc Nursing",
          "State Paramedical Entrance Exams",
          "Pharmacy Entrance Exams",
          "National Level MBA/PGDM",
          "CAT (Common Admission Test) - IIMS",
          "XAT (Xavier Aptitude Test)",
          "CMAT (Common Management Admission Test)",
          "MAT (Management Aptitude Test)",
          "ATMA (AIMS Test for Management Admissions)",
          "NMAT by GMAC (Narsee Monjee)",
          "SNAP (Symbiosis National Aptitude Test)",
          "IIFT (Indian Institute of Foreign Trade)",
          "TISSNET (Tata Institute of Social Sciences)",
          "MICAT (MICA Admission Test)",
          "IBSAT (ICFAI Business School Aptitude Test)",
          "Integrated & UG Management",
          "IPMAT (IIM Indore & Rohtak)",
          "NPAT (NMIMS Programs After Twelfth)",
          "SET (Symbiosis Entrance Test)",
          "Christ University Entrance",
          "DU JAT (Delhi University Joint Admission Test)",
          "CLAT (Common Law Admission Test) - UG & PG",
          "AILET (All India Law Entrance Test) - NLU Delhi",
          "LSAT India (Law School Admission Test)",
          "SLAT (Symbiosis Law Admission Test)",
          "Christ University Law Entrance",
          "IPU CET (Guru Gobind Singh Indraprastha University)",
          "Jindal Global Law School Entrance",
          "BLAT (Bennett Law Aptitude Test)",
          "DU LLB Entrance",
          "BHU UET (Law)",
          "AMU Law Entrance",
          "Jamia Millia Islamia Law Entrance",
          "UCEED (Undergraduate Common Entrance Exam for Design) - IIT",
          "CEED (Common Entrance Exam for Design) - IIT Postgraduate",
          "NID DAT (National Institute of Design - Design Aptitude Test)",
          "NIFT Entrance Exam",
          "PEARL (Pearl Academy Entrance Exam)",
          "SEED (Srishti Entrance Exam for Design)",
          "MIT Institute of Design Entrance",
          "Symbiosis Institute of Design Entrance",
          "FDDI (Footwear Design & Development Institute)",
          "AIFD (Army Institute of Fashion & Design)",
          "NIFT",
          "NID",
          "IIAD (Indian Institute of Art & Design)",
          "Arch Academy Entrance",
          "JJ School of Applied Art Entrance",
          "NCHMCT JEE (National Council for Hotel Management Joint Entrance Exam)",
          "IHM Entrance Exams (State-wise)",
          "AIMA UGAT (Hotel Management)",
          "WIHM Entrance",
          "BHM Entrance (Various Universities)",
          "IIMC Entrance (Indian Institute of Mass Communication)",
          "JMI Mass Communication Entrance",
          "DUET (Delhi University) - Journalism",
          "Symbiosis Entrance (Mass Communication)",
          "Xavier Institute of Communication Entrance",
          "Asian College of Journalism (ACJ)",
          "IP University CET (Mass Communication)",
          "NIMCET (NIT MCA Common Entrance Test)",
          "BIT MCA Entrance",
          "VIT MCA Entrance",
          "IPU CET (MCA)",
          "State University MCA Entrances",
          "IGRUA (Indira Gandhi Rashtriya Uran Akademi)",
          "NDA (for Indian Air Force)",
          "Pilot Training Entrance Exams",
          "Cabin Crew Entrance",
          "ICAR AIEEA (UG & PG)",
          "State Agriculture University Entrances",
          "Veterinary Entrance Exams",
          "GPAT (Graduate Pharmacy Aptitude Test)",
          "State Pharmacy Entrance Exams",
          "TISS NET (Tata Institute of Social Sciences)",
          "DU Entrance (Social Work)",
          "IGNOU MSW Entrance",
          "UGC NET (Library & Information Science)",
          "National Science Olympiad (NSO)",
          "National Cyber Olympiad (NCO)",
          "International Mathematics Olympiad (IMO)",
          "International English Olympiad (IEO)",
          "Science Olympiad Foundation (SOF) Exams",
          "NTSE (National Talent Search Examination)",
          "KVPY (Kishore Vaigyanik Protsahan Yojana)",
          "NMMS (National Means cum Merit Scholarship)",
          "JSTSE (Junior Science Talent Search Examination)",
          "NTSE",
          "NMMS",
          "INSPIRE",
          "Pre-RMO (Regional Mathematical Olympiad)",
          "RMO",
          "INMO (Indian National Mathematical Olympiad)",
          "Sainik School Entrance (AISSEE)",
          "Jawahar Navodaya Vidyalaya Selection Test (JNVST)",
          "Army Public School Entrance",
          "Delhi Public School Entrance",
          "Various Private School Entrances",
          "IELTS (International English Language Testing System)",
          "TOEFL (Test of English as a Foreign Language)",
          "PTE (Pearson Test of English)",
          "Duolingo English Test",
          "Cambridge English Exams (FCE, CAE, CPE)",
          "GRE (Graduate Record Examination)",
          "GMAT (Graduate Management Admission Test)",
          "SAT (Scholastic Assessment Test)",
          "ACT (American College Testing)",
          "MCAT (Medical College Admission Test)",
          "LSAT (Law School Admission Test - US)",
          "PCAT (Pharmacy College Admission Test)",
          "DAT (Dental Admission Test)",
          "OAT (Optometry Admission Test)",
          "AP (Advanced Placement) Exams",
          "IB (International Baccalaureate) Preparation",
          "CFA (Chartered Financial Analyst)",
          "FRM (Financial Risk Manager)",
          "ACCA (Association of Chartered Certified Accountants)",
          "CPA (Certified Public Accountant - US)",
          "CMA (Certified Management Accountant - US)",
          "CIA (Certified Internal Auditor)",
          "CISA (Certified Information Systems Auditor)",
          "PMP (Project Management Professional)",
          "PRINCE2",
          "ITIL",
          "CEH (Certified Ethical Hacker)",
          "CISSP (Certified Information Systems Security Professional)",
          "Python Programming",
            "Java Programming",
            "C Programming",
            "C++ Programming",
            "C# Programming",
            "JavaScript",
            "TypeScript",
            "Ruby",
            "PHP",
            "Go (Golang)",
            "Rust",
            "Kotlin",
            "Swift",
            "Objective-C",
            "Scala",
            "Perl",
            "R Programming",
            "MATLAB",
            "Julia",
            "HTML5 & CSS3",
            "Frontend Development",
            "Backend Development",
            "Full Stack Development",
            "React.js",
            "Angular",
            "Vue.js",
            "Node.js",
            "Express.js",
            "Django",
            "Flask",
            "Ruby on Rails",
            "ASP.NET",
            "Laravel",
            "WordPress Development",
            "Shopify Development",
            "Responsive Web Design",
            "Progressive Web Apps (PWA)",
            "Web Performance Optimization",
            "Android Development",
            "iOS Development",
            "React Native",
            "Flutter",
            "Ionic",
            "Xamarin",
            "Cross-Platform Development",
            "Mobile UI/UX Design",
            "App Store Optimization",
            "SQL & Database Management",
            "MySQL",
            "PostgreSQL",
            "MongoDB",
            "Oracle Database",
            "Microsoft SQL Server",
            "Redis",
            "Cassandra",
            "DynamoDB",
            "Firebase",
            "Database Design & Architecture",
            "Database Administration (DBA)",
            "DevOps Fundamentals",
            "Docker & Containerization",
            "Kubernetes",
            "Jenkins",
            "Git & GitHub",
            "GitLab CI/CD",
            "AWS (Amazon Web Services)",
            "Microsoft Azure",
            "Google Cloud Platform (GCP)",
            "Cloud Architecture",
            "Infrastructure as Code (Terraform, Ansible)",
            "Linux Administration",
            "Server Management",
            "Microservices Architecture",
            "Data Science Fundamentals",
            "Data Analysis",
            "Data Visualization",
            "Business Intelligence (BI)",
            "Tableau",
            "Power BI",
            "Excel Advanced & Data Analytics",
            "Google Data Analytics",
            "Statistical Analysis",
            "Predictive Analytics",
            "Big Data Analytics",
            "Apache Hadoop",
            "Apache Spark",
            "Data Engineering",
            "ETL (Extract, Transform, Load)",
            "SQL for Data Analysis",
            "Machine Learning Fundamentals",
            "Deep Learning",
            "Neural Networks",
            "Computer Vision",
            "Natural Language Processing (NLP)",
            "AI & ML with Python",
            "TensorFlow",
            "PyTorch",
            "Scikit-learn",
            "Keras",
            "Reinforcement Learning",
            "GANs (Generative Adversarial Networks)",
            "MLOps",
            "AI Ethics",
            "Ethical Hacking",
            "Penetration Testing",
            "Network Security",
            "Information Security",
            "Cyber Security Fundamentals",
            "CEH (Certified Ethical Hacker) Prep",
            "CISSP Prep",
            "Security+",
            "Web Application Security",
            "Cloud Security",
            "Malware Analysis",
            "Digital Forensics",
            "Incident Response",
            "Security Operations Center (SOC)",
            "Cryptography",
            "Blockchain Fundamentals",
            "Cryptocurrency & Bitcoin",
            "Ethereum & Smart Contracts",
            "Solidity Programming",
            "Web3 Development",
            "NFT Development",
            "DeFi (Decentralized Finance)",
            "Blockchain for Business",
            "Manual Testing",
            "Automation Testing",
            "Selenium",
            "Appium",
            "TestNG",
            "JUnit",
            "API Testing",
            "Performance Testing (JMeter, LoadRunner)",
            "Quality Assurance (QA)",
            "Test-Driven Development (TDD)",
            "UI/UX Design",
            "Figma",
            "Adobe XD",
            "Sketch",
            "InVision",
            "Wireframing & Prototyping",
            "User Research",
            "Usability Testing",
            "Design Thinking",
            "Product Design",
            "IT Project Management",
            "Agile & Scrum",
            "Software Architecture",
            "System Design",
            "Enterprise Architecture",
            "ITIL",
            "SAP",
            "Salesforce",
            "ServiceNow",
            "Unity Game Development",
            "Unreal Engine",
            "Game Design",
            "3D Game Development",
            "Mobile Game Development",
            "VR/AR Game Development",
            "Internet of Things (IoT)",
            "Augmented Reality (AR)",
            "Virtual Reality (VR)",
            "Quantum Computing",
            "Edge Computing",
            "5G Technology",
            "Robotics Programming",
            "Embedded Systems",
            "Graphic Design Fundamentals",
            "Adobe Photoshop",
            "Adobe Illustrator",
            "CorelDRAW",
            "Adobe InDesign",
            "Canva for Professionals",
            "Logo Design",
            "Brand Identity Design",
            "Print Design",
            "Packaging Design",
            "Typography",
            "Color Theory",
            "Digital Illustration",
            "Vector Art",
            "Photo Editing & Retouching",
            "Video Editing",
            "Adobe Premiere Pro",
            "Final Cut Pro",
            "DaVinci Resolve",
            "After Effects",
            "Motion Graphics",
            "Animation",
            "2D Animation",
            "3D Animation (Blender, Maya, 3ds Max)",
            "VFX (Visual Effects)",
            "Cinematography",
            "Video Production",
            "YouTube Video Creation",
            "Short Film Making",
            "Photography Fundamentals",
            "Digital Photography",
            "Portrait Photography",
            "Wedding Photography",
            "Product Photography",
            "Fashion Photography",
            "Wildlife Photography",
            "Landscape Photography",
            "Street Photography",
            "Food Photography",
            "Real Estate Photography",
            "Drone Photography",
            "Photo Editing (Lightroom)",
            "Studio Lighting",
            "Commercial Photography",
            "Music Production",
            "Audio Engineering",
            "Sound Design",
            "Music Composition",
            "Digital Audio Workstation (Logic Pro, Ableton, FL Studio)",
            "Mixing & Mastering",
            "Voice Over Training",
            "Podcast Production",
            "Singing/Vocal Training",
            "Guitar/Piano/Drums (Various Instruments)",
            "Music Theory",
            "DJ Training",
            "Professional Makeup Artistry",
            "Bridal Makeup",
            "HD Makeup",
            "Special Effects Makeup",
            "Hair Styling",
            "Hair Cutting & Coloring",
            "Nail Art & Manicure",
            "Cosmetology",
            "Beauty Therapy",
            "Spa Therapy",
            "Massage Therapy",
            "Aromatherapy",
            "Skincare Specialist",
            "Permanent Makeup (Microblading)",
            "Eyelash Extensions",
            "Fashion Design",
            "Fashion Illustration",
            "Pattern Making",
            "Garment Construction",
            "Fashion Styling",
            "Personal Styling",
            "Image Consulting",
            "Wardrobe Consulting",
            "Fashion Merchandising",
            "Textile Design",
                        "Digital Marketing",
            "Social Media Marketing",
            "Content Marketing",
            "Email Marketing",
            "SEO (Search Engine Optimization)",
            "SEM (Search Engine Marketing)",
            "Google Ads",
            "Facebook Ads",
            "Instagram Marketing",
            "LinkedIn Marketing",
            "Influencer Marketing",
            "Affiliate Marketing",
            "Growth Hacking",
            "Marketing Analytics",
            "Brand Management",
            "Public Relations (PR)",
            "Sales Techniques",
            "B2B Sales",
            "Negotiation Skills",
            "Customer Relationship Management (CRM)",
            "Business Strategy",
            "Business Development",
            "Operations Management",
            "Project Management (PMP, PRINCE2)",
            "Entrepreneurship",
            "Startup Management",
            "Business Planning",
            "Lean Management",
            "Six Sigma",
            "Change Management",
            "Risk Management",
            "Strategic Planning",
            "Financial Analysis",
            "Financial Modeling",
            "Investment Banking",
            "Equity Research",
            "Portfolio Management",
            "Personal Finance",
            "Wealth Management",
            "Tax Planning",
            "Bookkeeping",
            "QuickBooks",
            "Tally",
            "GST (Goods & Services Tax)",
            "Accounting Fundamentals",
            "Corporate Finance",
            "HR Management",
            "Talent Acquisition & Recruitment",
            "Employee Relations",
            "Performance Management",
            "Compensation & Benefits",
            "HR Analytics",
            "Organizational Development",
            "Training & Development",
            "Labour Laws",
            "Payroll Management",
            "Supply Chain Management",
            "Logistics Management",
            "Inventory Management",
            "Warehouse Management",
            "Procurement",
            "Import Export Management",
            "Custom Clearance",
            "English Speaking & Communication",
            "IELTS Preparation",
            "TOEFL Preparation",
            "PTE Preparation",
            "Business English",
            "French Language",
            "German Language",
            "Spanish Language",
            "Mandarin Chinese",
            "Japanese Language",
            "Korean Language",
            "Arabic Language",
            "Italian Language",
            "Portuguese Language",
            "Russian Language",
            "Dutch Language",
            "Hindi for Foreigners",
            "Sanskrit Language",
            "Public Speaking",
            "Presentation Skills",
            "Business Communication",
            "Email Writing",
            "Report Writing",
            "Technical Writing",
            "Creative Writing",
            "Copywriting",
            "Content Writing",
            "Blogging",
            "Storytelling",
            "Interpersonal Skills",
            "Leadership Skills",
            "Team Management",
            "Time Management",
            "Emotional Intelligence",
            "Conflict Resolution",
            "Critical Thinking",
            "Problem Solving",
            "Decision Making",
            "Personal Training",
            "Yoga Teacher Training (200hr, 500hr)",
            "Pilates Instructor",
            "Zumba Instructor",
            "Aerobics Instructor",
            "CrossFit Training",
            "Nutrition & Diet Planning",
            "Sports Nutrition",
            "Weight Loss Coaching",
            "Fitness Coaching",
            "Strength & Conditioning",
            "Meditation & Mindfulness",
            "Pranayama",
            "Reiki Healing",
            "Alternative Therapy",
            "Cooking Classes (Various Cuisines)",
            "Baking & Pastry",
            "Cake Decorating",
            "Chocolate Making",
            "Indian Cuisine",
            "Chinese Cuisine",
            "Italian Cuisine",
            "Continental Cuisine",
            "Bakery Management",
            "Food Styling & Photography",
            "Barista Training",
            "Bartending",
            "Wine Sommelier",
            "Food Safety & Hygiene",
             "Acting",
            "Theatre Arts",
            "Dance (Classical/Contemporary)",
            "Bharatanatyam",
            "Kathak",
            "Hip Hop Dance",
            "Salsa",
            "Ballet",
            "Stage Performance",
            "Stand-up Comedy",
            "Improv Comedy",
            "Mimicry & Voice Modulation",
            "Handmade Jewelry Making",
            "Pottery & Ceramics",
            "Candle Making",
            "Soap Making",
            "Paper Crafts",
            "Origami",
            "Crochet & Knitting",
            "Embroidery",
            "Painting (Oil, Acrylic, Watercolor)",
            "Sketching & Drawing",
            "Calligraphy",
            "Rangoli & Mandala Art",
            "Resin Art",
            "Macrame",
            "Interior Design",
            "Interior Decoration",
            "Vastu Shastra",
            "Feng Shui",
            "Furniture Design",
            "3D Visualization (SketchUp, 3ds Max)",
            "AutoCAD for Interiors",
            "Home Staging",
            "Event Planning & Management",
            "Wedding Planning",
            "Corporate Event Management",
            "Hotel Management",
            "Front Office Operations",
            "Housekeeping Management",
            "Food & Beverage Service",
            "Hospitality Management",
             "Car Driving",
            "Bike Riding",
            "Automobile Repair & Maintenance",
            "Two-Wheeler Mechanics",
            "Four-Wheeler Mechanics",
            "Electrical Vehicle Training",
            "Diesel Mechanics",
            "Tailoring & Stitching",
            "Garment Making",
            "Screen Printing",
            "Mobile Repairing",
            "Computer Hardware",
            "AC & Refrigeration Repair",
            "Electrical Work",
            "Plumbing",
            "Carpentry",
            "Welding",
            "Painting (Walls)",
            "Tile Fitting",
            "Security Guard Training",
            "Housekeeping",
            "Patient Care Attendant",
            "First Aid & CPR",
            "Real Estate Sales",
            "Property Management",
            "Real Estate Investment",
            "Real Estate Marketing",
            "RERA Compliance",
            "Organic Farming",
            "Hydroponics",
            "Terrace Gardening",
            "Mushroom Cultivation",
            "Vermicomposting",
            "Beekeeping",
            "Poultry Farming",
            "Dairy Farming",
            "Dog Training",
            "Pet Grooming",
            "Pet Care & Management",
            "Veterinary Assistant"
    )
    .required()
    .messages({
        "string.empty": "Please select a subDomain type.",
        "any.required": "Please select a subDomain type.",
        "any.only": "Please select a valid subDomain type from the list."
    });

export const courseHighlightsRule = Joi.string()
    .min(3)
    .max(200)
    .pattern(/^(?=.*[A-Za-z])[A-Za-z0-9\s.&'-,]+$/) // must contain at least one letter
    .required()
    .messages({
      "string.empty": "Course Highlights is required",
      "string.min": "Course Highlights must be at least 3 characters",
      "string.max": "Course Highlights must be at most 200 characters",
      "string.pattern.base":
        "Course Highlights must contain at least one letter and can only include letters, numbers, spaces, . & ' - ,",
    });
  // In ValidationRules.ts

export const durationRule = Joi.string()
  .min(5)
  .max(20)
  .pattern(/^\d+ (year|month|week|day)s?$/i)
  .required()
  .messages({
    "string.empty": "Course duration is required",
    // ✅ ADD THIS LINE to customize the minimum length error message
    "string.min": "Course duration is too short, use a valid format like '6 months or 1 year'",
    "string.max": "Course duration is too long",
    "string.pattern.base": "Duration must be in a format like '6 months' or '1 year'",
    "any.required": "Course duration is required",
  });
// Phone number validation (exactly 10 digits)
export const phoneRule = Joi.string()
  // This new pattern ensures the first digit is 6, 7, 8, or 9
  .pattern(/^[6-9]\d{9}$/)
  .required()
  .messages({
    "string.empty": "Phone number is required.",
    "string.pattern.base": "Please enter a valid 10-digit Indian mobile number.",
    "any.required": "Phone number is required.",
  });

// Pincode validation (6 digits)
export const pincodeRule = Joi.string()
  .pattern(/^\d{6}$/)
  .required()
  .messages({
    "string.empty": "Pincode is required",
    "string.pattern.base": "Pincode must be exactly 6 digits",
    "any.required": "Pincode is required",
  });

// State validation
export const stateRule = Joi.string()
  .min(2)
  .max(50)
  .required()
  .messages({
    "string.empty": "State is required",
    "string.min": "State must be at least 2 characters",
    "string.max": "State cannot exceed 50 characters",
    "any.required": "State is required",
  });

// URL validation (must start with http:// or https://)
export const urlRule = Joi.string()
  .pattern(/^https?:\/\/.+/) // This checks for "http://" or "https://"
  .required()
  .messages({
    'string.empty': 'URL is required',
    // ✅ This line provides the custom error message for the pattern
    'string.pattern.base': 'URL must start with http:// or https://', 
    'any.required': 'URL is required',
  });

  export const createdBranchRule = Joi.string().required().messages({
  "string.empty": "Please select a branch for the course.",
  "any.required": "Please select a branch for the course.",
});

// ✅ Rule for Graduation Type dropdown
export const graduationTypeRule = Joi.string().required().messages({
  "string.empty": "Please select a graduation type.",
  "any.required": "Please select a graduation type.",
});

// ✅ Rule for Stream Type dropdown
export const streamTypeRule = Joi.string().required().messages({
  "string.empty": "Please select a stream type.",
  "any.required": "Please select a stream type.",
});

// ✅ Rule for the 'Select branch' dropdown in the UG/PG form
export const selectBranchRule = Joi.string().required().messages({
  "string.empty": "Please select a branch.",
  "any.required": "Please select a branch.",
});
// -----------------------------
// Branch-specific reusable rules
// -----------------------------
export const branchNameRule = alphaNumericNameRule; // letters, numbers, spaces
export const branchPhoneRule = phoneRule;           // reuse phoneRule
export const branchUrlRule = urlRule;              // reuse urlRule
